module.exports = {
  name: "interactionCreate",
  async execute(interaction) {
    const { options, commandName } = interaction;
    if (interaction.isAutocomplete()) {
      if (commandName === "localize" || commandName === "preview") {
        const focusedValue = options.getFocused();
        var choices = [
          "English",
          "Spanish",
          "French",
          "Croatian",
          "Arabic",
          "Russian",
          "German",
          "Portuguese",
          "Japanese",
          "Italian",
          "Dutch",
          "Korean",
          "Greek",
          "Polish",
          "Turkish",
          "Swedish",
          "Danish",
          "Hindi",
          "Finnish",
          "Czech",
          "Slovak",
          "Hungarian",
          "Thai",
          "Romanian",
          "Urdu",
          "Afrikaans",
          "Albanian",
          "Amharic",
          "Armenian",
          "Azerbaijani",
          "Basque",
          "Belarusian",
          "Bengali",
          "Bosnian",
          "Bulgarian",
          "Catalan",
          "Cebuano",
          "Chichewa",
          "Chinese Simplified",
          "Chinese Traditional",
          "Corsican",
          "Esperanto",
          "Estonian",
          "Filipino",
          "Frisian",
          "Galician",
          "Georgian",
          "Gujarati",
          "Haitian Creole",
          "Hausa",
          "Hawaiian",
          "Hebrew",
          "Hmong",
          "Icelandic",
          "Igbo",
          "Indonesian",
          "Irish",
          "Javanese",
          "Kannada",
          "Kazakh",
          "Khmer",
          "Kurdish (Kurmanji)",
          "Kyrgyz",
          "Lao",
          "Latin",
          "Latvian",
          "Lithuanian",
          "Luxembourgish",
          "Macedonian",
          "Malagasy",
          "Malay",
          "Malayalam",
          "Maltese",
          "Maori",
          "Marathi",
          "Mongolian",
          "Myanmar (Burmese)",
          "Nepali",
          "Norwegian",
          "Pashto",
          "Persian",
          "Punjabi",
          "Samoan",
          "Scots Gaelic",
          "Serbian",
          "Sesotho",
          "Shona",
          "Sindhi",
          "Sinhala",
          "Slovenian",
          "Somali",
          "Sundanese",
          "Swahili",
          "Tajik",
          "Tamil",
          "Telugu",
          "Ukrainian",
          "Uzbek",
          "Vietnamese",
          "Welsh",
          "Xhosa",
          "Yiddish",
          "Yoruba",
          "Zulu",
        ];
        const filtered = choices.filter((choice) =>
          choice.startsWith(focusedValue)
        );
        await interaction.respond(
          filtered
            .map((choice) => ({ name: choice, value: choice }))
            .slice(0, 25)
        );
      }
    }
  },
};
